# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeoFood' do
	pod 'Alamofire', '~> 5.4.1'
end

target 'GeoFoodTests' do
    pod 'Alamofire', '~> 5.4.1'
end

